// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Transaction.Domain.AggreagatesModels.Aggregate;
using Transaction.Infrastructure.DataBase;

namespace Transaction.Infrastructure.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20190821125946_Initial2")]
    partial class Initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Transaction.Domain.AggreagatesModels.Aggregate.BuyerData", b =>
                {
                    b.Property<Guid>("BuyId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("BuyPrice");

                    b.Property<decimal>("BuyQuantity");

                    b.Property<DateTime>("InsertTime");

                    b.Property<decimal>("RemainingQuantity");

                    b.Property<decimal>("SettledQuantity");

                    b.Property<int>("TransactionStatus");

                    b.HasKey("BuyId");

                    b.ToTable("BuyerDatas");
                });

            modelBuilder.Entity("Transaction.Domain.AggreagatesModels.Aggregate.Ledger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BuyerId")
                        .HasMaxLength(50);

                    b.Property<double>("BuyerPrice");

                    b.Property<string>("DisplayId")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ProcessTime");

                    b.Property<string>("SellerId")
                        .HasMaxLength(50);

                    b.Property<double>("SellerPrice");

                    b.Property<long>("SellerQuantity");

                    b.Property<int>("TransactionStatus");

                    b.HasKey("Id");

                    b.ToTable("Ledgers");
                });

            modelBuilder.Entity("Transaction.Domain.AggreagatesModels.Aggregate.SellerData", b =>
                {
                    b.Property<Guid>("SellerId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertTime");

                    b.Property<decimal>("RemainingQuantity");

                    b.Property<decimal>("SellPrice");

                    b.Property<decimal>("SellQuantity");

                    b.Property<decimal>("SettledQuantity");

                    b.Property<int>("TransactionStatus");

                    b.HasKey("SellerId");

                    b.ToTable("SellerDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
