// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Transaction.Infrastructure.Database;

namespace Transaction.Infrastructure.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    partial class TransactionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Transaction.Domain.AggreagatesModels.BuyerAggregate.Buyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BuyerTransactionStatusId");

                    b.Property<decimal>("Price");

                    b.Property<decimal>("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("BuyerTransactionStatusId");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("Transaction.Domain.AggreagatesModels.BuyerAggregate.BuyerInformartion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(28,18)");

                    b.Property<byte[]>("TimeStamps")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<decimal>("Total");

                    b.Property<int>("TransationStatus");

                    b.HasKey("Id");

                    b.ToTable("BuyerInformartion","dbo");
                });

            modelBuilder.Entity("Transaction.Domain.AggreagatesModels.BuyerAggregate.BuyerTransactionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("BuyerTransactionStatus");
                });

            modelBuilder.Entity("Transaction.Domain.AggreagatesModels.BuyerAggregate.Buyer", b =>
                {
                    b.HasOne("Transaction.Domain.AggreagatesModels.BuyerAggregate.BuyerTransactionStatus", "BuyerTransactionStatus")
                        .WithMany()
                        .HasForeignKey("BuyerTransactionStatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
